import type { Metadata } from "next";
import { Geist, Geist_Mono, Michroma } from "next/font/google";
import "./globals.css";
import LightingBackground from "@/components/LightingBackground";
import Image from "next/image";
import AnimatedBackground from "@/components/AnimatedBackground";

const michromaMono = Michroma({
  variable: "--font-michroma",
  subsets: ["latin"],
  weight: ["400"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${michromaMono.variable} antialiased `}>
        <AnimatedBackground />
        {children}
      </body>
    </html>
  );
}
